### ISSUE TITLE
ValueError: Initial pipeline fit was failed due to: /home/hemang/anaconda3/lib/libxgboost.so: undefined symbol: XGDMatrixCreateFromDense. Check pipeline structure and the correctness of the data

### ISSUE THREAD

**Issue by hemangjoshi37a** [nccr-itmo/FEDOT#595] opened 2022-03-13 18:48 UTC
2022-03-14 00:17:24.473694: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-14 00:17:24.473730: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/fedot/api/api_utils/api_composer.py", line 325, in fit_and_check_correctness
    initial_pipelines[0].fit(data)
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/fedot/core/pipelines/pipeline.py", line 156, in fit
    train_predicted = self._fit(input_data=copied_input_data,
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/fedot/core/pipelines/pipeline.py", line 119, in _fit
    train_predicted = self.root_node.fit(input_data=input_data)
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/fedot/core/pipelines/node.py", line 257, in fit
    return super().fit(input_data)
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/fedot/core/pipelines/node.py", line 160, in fit
    self.fitted_operation, operation_predict = self.operation.fit(params=self.content['params'],
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/fedot/core/operations/operation.py", line 82, in fit
    self.fitted_operation = self._eval_strategy.fit(train_data=data)
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/fedot/core/operations/evaluation/evaluation_interfaces.py", line 186, in fit
    operation_implementation.fit(train_data.features, train_data.target)
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/xgboost/core.py", line 506, in inner_f
    return f(**kwargs)
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py", line 1231, in fit
    train_dmatrix, evals = _wrap_evaluation_matrices(
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py", line 286, in _wrap_evaluation_matrices
    train_dmatrix = create_dmatrix(
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py", line 1245, in <lambda>
    create_dmatrix=lambda **kwargs: DMatrix(nthread=self.n_jobs, **kwargs),
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/xgboost/core.py", line 506, in inner_f
    return f(**kwargs)
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/xgboost/core.py", line 616, in __init__
    handle, feature_names, feature_types = dispatch_data_backend(
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/xgboost/data.py", line 763, in dispatch_data_backend
    return _from_numpy_array(data, missing, threads, feature_names,
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/xgboost/data.py", line 179, in _from_numpy_array
    _LIB.XGDMatrixCreateFromDense(
  File "/home/hemang/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/home/hemang/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/hemang/anaconda3/lib/libxgboost.so: undefined symbol: XGDMatrixCreateFromDense

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/lib/python3.8/site-packages/fedot/api/api_utils/api_composer.py in fit_and_check_correctness(initial_pipelines, data, logger)
    324         _, data_test = train_test_data_setup(data)
--> 325         initial_pipelines[0].fit(data)
    326         initial_pipelines[0].predict(data_test)

~/anaconda3/lib/python3.8/site-packages/fedot/core/pipelines/pipeline.py in fit(self, input_data, use_fitted, time_constraint)
    155         if time_constraint is None:
--> 156             train_predicted = self._fit(input_data=copied_input_data,
    157                                         use_fitted_operations=use_fitted)

~/anaconda3/lib/python3.8/site-packages/fedot/core/pipelines/pipeline.py in _fit(self, input_data, use_fitted_operations, process_state_dict, fitted_operations)
    118                                       self.computation_time is None
--> 119             train_predicted = self.root_node.fit(input_data=input_data)
    120             if computation_time_update:

~/anaconda3/lib/python3.8/site-packages/fedot/core/pipelines/node.py in fit(self, input_data, **kwargs)
    256             self.node_data = input_data
--> 257         return super().fit(input_data)
    258 

~/anaconda3/lib/python3.8/site-packages/fedot/core/pipelines/node.py in fit(self, input_data)
    159         if self.fitted_operation is None:
--> 160             self.fitted_operation, operation_predict = self.operation.fit(params=self.content['params'],
    161                                                                           data=input_data,

~/anaconda3/lib/python3.8/site-packages/fedot/core/operations/operation.py in fit(self, params, data, is_fit_pipeline_stage)
     81 
---> 82         self.fitted_operation = self._eval_strategy.fit(train_data=data)
     83 

~/anaconda3/lib/python3.8/site-packages/fedot/core/operations/evaluation/evaluation_interfaces.py in fit(self, train_data)
    185         else:
--> 186             operation_implementation.fit(train_data.features, train_data.target)
    187         return operation_implementation

~/anaconda3/lib/python3.8/site-packages/xgboost/core.py in inner_f(*args, **kwargs)
    505             kwargs[k] = arg
--> 506         return f(**kwargs)
    507 

~/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py in fit(self, X, y, sample_weight, base_margin, eval_set, eval_metric, early_stopping_rounds, verbose, xgb_model, sample_weight_eval_set, base_margin_eval_set, feature_weights, callbacks)
   1230         model, feval, params = self._configure_fit(xgb_model, eval_metric, params)
-> 1231         train_dmatrix, evals = _wrap_evaluation_matrices(
   1232             missing=self.missing,

~/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py in _wrap_evaluation_matrices(missing, X, y, group, qid, sample_weight, base_margin, feature_weights, eval_set, sample_weight_eval_set, base_margin_eval_set, eval_group, eval_qid, create_dmatrix, enable_categorical, label_transform)
    285     """
--> 286     train_dmatrix = create_dmatrix(
    287         data=X,

~/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py in <lambda>(**kwargs)
   1244             eval_qid=None,
-> 1245             create_dmatrix=lambda **kwargs: DMatrix(nthread=self.n_jobs, **kwargs),
   1246             enable_categorical=self.enable_categorical,

~/anaconda3/lib/python3.8/site-packages/xgboost/core.py in inner_f(*args, **kwargs)
    505             kwargs[k] = arg
--> 506         return f(**kwargs)
    507 

~/anaconda3/lib/python3.8/site-packages/xgboost/core.py in __init__(self, data, label, weight, base_margin, missing, silent, feature_names, feature_types, nthread, group, qid, label_lower_bound, label_upper_bound, feature_weights, enable_categorical)
    615 
--> 616         handle, feature_names, feature_types = dispatch_data_backend(
    617             data,

~/anaconda3/lib/python3.8/site-packages/xgboost/data.py in dispatch_data_backend(data, missing, threads, feature_names, feature_types, enable_categorical)
    762     if _is_numpy_array(data):
--> 763         return _from_numpy_array(data, missing, threads, feature_names,
    764                                  feature_types)

~/anaconda3/lib/python3.8/site-packages/xgboost/data.py in _from_numpy_array(data, missing, nthread, feature_names, feature_types)
    178     _check_call(
--> 179         _LIB.XGDMatrixCreateFromDense(
    180             _array_interface(data),

~/anaconda3/lib/python3.8/ctypes/__init__.py in __getattr__(self, name)
    393             raise AttributeError(name)
--> 394         func = self.__getitem__(name)
    395         setattr(self, name, func)

~/anaconda3/lib/python3.8/ctypes/__init__.py in __getitem__(self, name_or_ordinal)
    398     def __getitem__(self, name_or_ordinal):
--> 399         func = self._FuncPtr((name_or_ordinal, self))
    400         if not isinstance(name_or_ordinal, int):

AttributeError: /home/hemang/anaconda3/lib/libxgboost.so: undefined symbol: XGDMatrixCreateFromDense

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/tmp/ipykernel_6827/2888392436.py in <module>
      5 
      6 # fit model without optimisation - single XGBoost node is used
----> 7 xgb_pipeline = baseline_model.fit(features=train_data_path, target='tgt_high', predefined_model='xgboost')
      8 
      9 # evaluate the prediction with test data

~/anaconda3/lib/python3.8/site-packages/fedot/api/main.py in fit(self, features, target, predefined_model)
    143         if predefined_model is not None:
    144             # Fit predefined model and return it without composing
--> 145             self.current_pipeline = self._process_predefined_model(predefined_model)
    146         else:
    147             if self.timeout_set_in_init is not None:

~/anaconda3/lib/python3.8/site-packages/fedot/api/main.py in _process_predefined_model(self, predefined_model)
    414 
    415         # Perform fitting
--> 416         fit_and_check_correctness(pipelines, data=self.train_data,
    417                                   logger=self.params.api_params['logger'])
    418         return pipelines[0]

~/anaconda3/lib/python3.8/site-packages/fedot/api/api_utils/api_composer.py in fit_and_check_correctness(initial_pipelines, data, logger)
    334         logger.info(fit_failed_info)
    335         print(traceback.format_exc())
--> 336         raise ValueError(advice_info)
    337 
    338 

ValueError: Initial pipeline fit was failed due to: /home/hemang/anaconda3/lib/libxgboost.so: undefined symbol: XGDMatrixCreateFromDense. Check pipeline structure and the correctness of the data

**Comment by Dreamlone** [comment] 2022-03-14 07:38
Hi! Please provide the data and the code you ran, so we can reproduce the error. It is also worth specifying the framework version. It would be most reliable to make a separate branch in the repository (or fork) with the example code and data

Also, it looks like this is not a problem on the FEDOT side. Check this [issue](https://github.com/abhishekkrthakur/autoxgb/issues/4), reinstalling xgboost helped

**Comment by nicl-nno** [comment] 2022-05-21 19:40
Closed as obsolete.
Pls reopen it if the problem is still actual.

**Closed by nicl-nno** 2022-05-21 19:40 UTC
